# Generated by Django 4.2 on 2023-05-12 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_savedposts_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedposts',
            old_name='saved_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
