# Generated by Django 4.2 on 2023-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_commented_user_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
