# Generated by Django 4.2 on 2023-05-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_addfriend_created_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
