# Generated by Django 4.2 on 2023-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_notification_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addFriend',
            new_name='Friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='following_user',
            new_name='follow_user',
        ),
    ]
