# Generated by Django 4.2 on 2023-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_chats_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
