# Generated by Django 4.2 on 2023-05-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='content',
        ),
    ]
